"""Configuration documentation generator.

Produces human-readable configuration documentation in Markdown and HTML
from analysis results, suitable for inclusion in project READMEs or as
standalone reference documents.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

    from envtether.models.config import ConfigVariable
    from envtether.models.report import FullReport

logger = logging.getLogger(__name__)


class DocumentationGenerator:
    """Generates configuration documentation from analysis results."""

    def generate_markdown(self, report: FullReport) -> str:
        """Generate Markdown configuration documentation.

        Args:
            report: The full analysis report.

        Returns:
            A Markdown string documenting all configuration variables.
        """
        lines: list[str] = [
            "# Configuration Reference",
            "",
            "This document is auto-generated by [envtether](https://github.com/envtether/envtether).",
            "",
        ]

        # Project info
        if report.project:
            lines.extend(
                [
                    "## Project Overview",
                    "",
                    f"- **Project**: {report.project.name}",
                    f"- **Files scanned**: {report.project.total_files_scanned}",
                    f"- **Configuration files**: {report.project.total_config_files}",
                    f"- **Python files**: {report.project.total_python_files}",
                ]
            )
            if report.project.architecture.project_types:
                types = ", ".join(
                    sorted(pt.value for pt in report.project.architecture.project_types)
                )
                lines.append(f"- **Frameworks**: {types}")
            if report.project.architecture.cloud_providers:
                providers = ", ".join(
                    sorted(cp.value for cp in report.project.architecture.cloud_providers)
                )
                lines.append(f"- **Cloud providers**: {providers}")
            lines.append("")

        # Group variables by source type
        grouped: dict[str, list[ConfigVariable]] = {}
        for var in report.variables:
            for source in var.sources:
                key = source.source_type.value.replace("_", " ").title()
                grouped.setdefault(key, []).append(var)
                break  # use first source for grouping

        # Variables by group
        lines.extend(["## Environment Variables", ""])

        for group_name, group_vars in sorted(grouped.items()):
            lines.extend([f"### {group_name}", ""])

            # Deduplicate
            seen: set[str] = set()
            for var in sorted(group_vars, key=lambda v: v.name):
                if var.name in seen:
                    continue
                seen.add(var.name)

                required = (
                    "**Required**" if any(s.is_required for s in var.sources) else "Optional"
                )
                secret = " 🔒 Secret" if var.is_secret else ""

                lines.append(f"#### `{var.name}`")
                lines.append("")

                if var.description:
                    lines.append(var.description)
                    lines.append("")

                lines.append(f"- **Status**: {required}{secret}")

                # Default value
                for source in var.sources:
                    if source.default_value:
                        default_display = source.default_value.raw
                        if source.is_secret:
                            default_display = "\\*\\*\\*\\*\\*\\*\\*\\*"
                        lines.append(f"- **Default**: `{default_display}`")
                        break

                # Sources
                source_files = sorted({s.location.file_path for s in var.sources})
                if source_files:
                    lines.append(f"- **Defined in**: {', '.join(f'`{f}`' for f in source_files)}")

                # Usages
                if var.usages:
                    usage_files = sorted({u.location.file_path for u in var.usages})
                    lines.append(f"- **Used in**: {', '.join(f'`{f}`' for f in usage_files)}")

                lines.append("")

        # Architecture
        if report.project and report.project.architecture.services:
            lines.extend(["## Service Dependencies", ""])
            lines.extend(
                [
                    "| Service | Role | Provider | Config Variables |",
                    "|---------|------|----------|-----------------|",
                ]
            )
            for svc in report.project.architecture.services:
                config_vars = ", ".join(f"`{v}`" for v in sorted(svc.config_variables)) or "—"
                lines.append(f"| {svc.name} | {svc.role.value} | {svc.provider} | {config_vars} |")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by [envtether](https://github.com/envtether/envtether)*")
        return "\n".join(lines)

    def generate_html(self, report: FullReport) -> str:
        """Generate HTML configuration documentation.

        Args:
            report: The full analysis report.

        Returns:
            A complete HTML document string.
        """
        md_content = self.generate_markdown(report)

        # Simple Markdown → HTML conversion for documentation
        html_body = self._simple_md_to_html(md_content)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Configuration Reference — envtether</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:'Inter',system-ui,sans-serif;background:#0f172a;color:#e2e8f0;line-height:1.7;padding:3rem}}
.container{{max-width:900px;margin:0 auto}}
h1{{font-size:2rem;font-weight:800;background:linear-gradient(135deg,#818cf8,#c084fc);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:1rem}}
h2{{font-size:1.5rem;font-weight:700;color:#c084fc;margin:2rem 0 1rem;padding-top:1rem;border-top:1px solid #1e293b}}
h3{{font-size:1.2rem;font-weight:600;color:#818cf8;margin:1.5rem 0 .5rem}}
h4{{font-size:1rem;font-weight:600;margin:1rem 0 .25rem}}
p{{margin:.5rem 0;color:#cbd5e1}}
ul,ol{{padding-left:1.5rem;margin:.5rem 0}}
li{{margin:.25rem 0;color:#94a3b8}}
code{{background:#1e293b;padding:2px 6px;border-radius:4px;font-size:.85rem;color:#818cf8}}
table{{width:100%;border-collapse:collapse;margin:1rem 0}}
th,td{{padding:.5rem 1rem;text-align:left;border-bottom:1px solid #1e293b}}
th{{color:#94a3b8;font-size:.75rem;text-transform:uppercase}}
hr{{border:none;border-top:1px solid #1e293b;margin:2rem 0}}
em{{color:#64748b;font-style:normal}}
</style>
</head>
<body>
<div class="container">
{html_body}
</div>
</body>
</html>"""

    def save(
        self,
        report: FullReport,
        output_path: Path,
        fmt: str = "markdown",
    ) -> Path:
        """Save documentation to a file.

        Args:
            report: The full analysis report.
            output_path: Target file path.
            fmt: Format (``markdown`` or ``html``).

        Returns:
            The path the file was written to.
        """
        content = self.generate_html(report) if fmt == "html" else self.generate_markdown(report)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
        logger.info("Documentation written to %s", output_path)
        return output_path

    @staticmethod
    def _simple_md_to_html(md: str) -> str:
        """Very basic Markdown to HTML for documentation rendering."""
        import re

        html_lines: list[str] = []
        in_table = False
        in_list = False

        for line in md.splitlines():
            stripped = line.strip()

            if stripped.startswith("# "):
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append(f"<h1>{stripped[2:]}</h1>")
            elif stripped.startswith("## "):
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append(f"<h2>{stripped[3:]}</h2>")
            elif stripped.startswith("### "):
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append(f"<h3>{stripped[4:]}</h3>")
            elif stripped.startswith("#### "):
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append(f"<h4>{stripped[5:]}</h4>")
            elif stripped.startswith("| ") and "---" not in stripped:
                if not in_table:
                    html_lines.append("<table><thead><tr>")
                    cells = [c.strip() for c in stripped.split("|")[1:-1]]
                    for cell in cells:
                        html_lines.append(f"<th>{cell}</th>")
                    html_lines.append("</tr></thead><tbody>")
                    in_table = True
                else:
                    html_lines.append("<tr>")
                    cells = [c.strip() for c in stripped.split("|")[1:-1]]
                    for cell in cells:
                        # Convert backtick code
                        cell_html = re.sub(r"`([^`]+)`", r"<code>\1</code>", cell)
                        html_lines.append(f"<td>{cell_html}</td>")
                    html_lines.append("</tr>")
            elif stripped.startswith("|---") or stripped.startswith("| ---"):
                continue
            elif stripped.startswith("- "):
                if in_table:
                    html_lines.append("</tbody></table>")
                    in_table = False
                if not in_list:
                    html_lines.append("<ul>")
                    in_list = True
                item = stripped[2:]
                item = re.sub(r"`([^`]+)`", r"<code>\1</code>", item)
                item = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", item)
                html_lines.append(f"<li>{item}</li>")
            elif stripped == "---":
                if in_table:
                    html_lines.append("</tbody></table>")
                    in_table = False
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append("<hr>")
            elif stripped.startswith("*") and stripped.endswith("*"):
                html_lines.append(f"<p><em>{stripped[1:-1]}</em></p>")
            elif stripped:
                if in_table:
                    html_lines.append("</tbody></table>")
                    in_table = False
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                line_html = re.sub(r"`([^`]+)`", r"<code>\1</code>", stripped)
                line_html = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", line_html)
                line_html = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', line_html)
                html_lines.append(f"<p>{line_html}</p>")

        if in_table:
            html_lines.append("</tbody></table>")
        if in_list:
            html_lines.append("</ul>")

        return "\n".join(html_lines)
